version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ../problems:/root/problems
      - ../.vscode:/root/problems/.vscode
    # C++ include-path for ACL or Boost library
    # Check ~/.bashrc or .bash_profile
    environment:
      - CPLUS_INCLUDE_PATH=${CPLUS_INCLUDE_PATH}

    command: /bin/sh -c "while sleep 1000; do :; done"
